-- =====================================================================
-- svings — complete schema + demo data, in one script.
--
-- Generated by concatenating supabase/migrations/* then supabase/seed/*
-- in dependency order. Do not edit here; edit the source files and
-- regenerate, otherwise this copy silently drifts.
--
-- HOW TO APPLY (no CLI, no password):
--   Supabase Dashboard -> SQL Editor -> New query -> paste this whole file -> Run
--
-- Safe to re-run? The migrations are idempotent (create table if not exists,
-- create or replace, type creation guarded by exception handlers). The SEED is
-- not: it deletes and recreates the demo users' rows. Only re-run the whole
-- thing against a database whose data you are happy to reset.
-- =====================================================================


-- #####################################################################
-- ## migrations/20260101000001_init_schema.sql
-- ## Schema: types, tables, indexes, triggers
-- #####################################################################

-- =====================================================================
-- Migration: 20260101000001_init_schema.sql
-- Purpose : Create the svings money-tracker schema.
-- Order    : Run first. Defines all types, tables, indexes, triggers.
--
-- Scope    : money tracking only. An earlier revision of this file also
--            defined a campus academic domain (faculties, programs,
--            lecturers, courses, students, enrollments, grades, attendance).
--            That was unrelated to this app and has been removed; it is in
--            git history if ever needed.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------
create extension if not exists "uuid-ossp";
create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------
-- Enumerated types
-- ---------------------------------------------------------------------
do $$ begin
  create type transaction_type as enum ('income', 'expense');
exception when duplicate_object then null; end $$;

-- How a transaction got recorded. Lets the UI distinguish entries the user
-- typed from entries the email sync produced.
do $$ begin
  create type transaction_source as enum ('manual', 'email');
exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------------
-- updated_at trigger function
-- ---------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- =====================================================================
-- 1. profiles — extends auth.users with app-specific fields
-- =====================================================================
create table if not exists public.profiles (
  id           uuid primary key references auth.users(id) on delete cascade,
  full_name    text        not null,
  email        text        not null unique,
  avatar_url   text,
  phone        text,
  is_active    boolean     not null default true,
  metadata     jsonb       not null default '{}'::jsonb,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists idx_profiles_email on public.profiles (email);

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

-- Auto-create a profile row when a new user signs up via Supabase Auth
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    new.email
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- =====================================================================
-- 2. raw_emails — fetched bank / e-wallet notification emails
--
-- Stored before parsing so that:
--   * a re-sync is idempotent — (user_id, message_id) is the dedupe key
--   * the parser can be improved later and re-run over the stored bodies
-- =====================================================================
create table if not exists public.raw_emails (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid        not null references public.profiles(id) on delete cascade,
  message_id   text        not null,        -- provider's message id (Gmail)
  thread_id    text,
  received_at  timestamptz,
  sender       text,
  subject      text,
  body         text        not null,
  parsed       boolean     not null default false,
  parse_error  text,                        -- why parsing failed, if it did
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (user_id, message_id)
);

create index if not exists idx_raw_emails_user_parsed on public.raw_emails (user_id, parsed);
create index if not exists idx_raw_emails_received on public.raw_emails (received_at desc);

drop trigger if exists trg_raw_emails_updated_at on public.raw_emails;
create trigger trg_raw_emails_updated_at
  before update on public.raw_emails
  for each row execute function public.set_updated_at();

-- =====================================================================
-- 3. transactions — the money entries
-- =====================================================================
create table if not exists public.transactions (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid        not null references public.profiles(id) on delete cascade,
  type         transaction_type not null,
  date         date        not null,
  total        numeric(14,2) not null check (total >= 0),
  notes        text,
  -- [{name, price}] where price is a STRING; see docs/DATABASE.md
  items        jsonb       not null default '[]'::jsonb,
  source       transaction_source not null default 'manual',
  raw_email_id uuid        references public.raw_emails(id) on delete set null,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists idx_transactions_user_date on public.transactions (user_id, date desc);
create index if not exists idx_transactions_type on public.transactions (type);
create index if not exists idx_transactions_user_type_date on public.transactions (user_id, type, date);
create index if not exists idx_transactions_raw_email on public.transactions (raw_email_id);

drop trigger if exists trg_transactions_updated_at on public.transactions;
create trigger trg_transactions_updated_at
  before update on public.transactions
  for each row execute function public.set_updated_at();

-- =====================================================================
-- Done.
-- =====================================================================

-- #####################################################################
-- ## migrations/20260101000002_rls_policies.sql
-- ## Row Level Security
-- #####################################################################

-- =====================================================================
-- Migration: 20260101000002_rls_policies.sql
-- Purpose : Enable RLS and define access policies.
--
-- Every table here is per-user private. There are no shared/reference tables
-- any more — the campus reference data they belonged to has been removed.
-- =====================================================================

-- ---------------------------------------------------------------------
-- profiles
-- ---------------------------------------------------------------------
alter table public.profiles enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles for select
  using (id = auth.uid());

drop policy if exists "profiles_insert_self" on public.profiles;
create policy "profiles_insert_self"
  on public.profiles for insert
  with check (id = auth.uid());

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles for update
  using (id = auth.uid())
  with check (id = auth.uid());

-- ---------------------------------------------------------------------
-- transactions — private to each user
-- ---------------------------------------------------------------------
alter table public.transactions enable row level security;

drop policy if exists "transactions_select_own" on public.transactions;
create policy "transactions_select_own"
  on public.transactions for select
  using (user_id = auth.uid());

drop policy if exists "transactions_insert_own" on public.transactions;
create policy "transactions_insert_own"
  on public.transactions for insert
  with check (user_id = auth.uid());

drop policy if exists "transactions_update_own" on public.transactions;
create policy "transactions_update_own"
  on public.transactions for update
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists "transactions_delete_own" on public.transactions;
create policy "transactions_delete_own"
  on public.transactions for delete
  using (user_id = auth.uid());

-- ---------------------------------------------------------------------
-- raw_emails — private to each user
--
-- The email body is the most sensitive thing this app stores, so it gets the
-- same four-policy treatment as transactions rather than anything looser.
-- ---------------------------------------------------------------------
alter table public.raw_emails enable row level security;

drop policy if exists "raw_emails_select_own" on public.raw_emails;
create policy "raw_emails_select_own"
  on public.raw_emails for select
  using (user_id = auth.uid());

drop policy if exists "raw_emails_insert_own" on public.raw_emails;
create policy "raw_emails_insert_own"
  on public.raw_emails for insert
  with check (user_id = auth.uid());

drop policy if exists "raw_emails_update_own" on public.raw_emails;
create policy "raw_emails_update_own"
  on public.raw_emails for update
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

drop policy if exists "raw_emails_delete_own" on public.raw_emails;
create policy "raw_emails_delete_own"
  on public.raw_emails for delete
  using (user_id = auth.uid());

-- #####################################################################
-- ## seed/99_demo_users.sql
-- ## Demo auth users + sample transactions
-- #####################################################################

-- =====================================================================
-- Seed: 99_demo_users.sql
-- Purpose: Create 2 demo auth users for the app + sample transactions.
--
-- IMPORTANT: Passwords are stored as bcrypt hashes. The plain-text
-- passwords are documented in supabase/README.md — these are DEMO
-- credentials, do NOT use in production.
-- =====================================================================

-- 1. Create demo users in auth.users (triggers will create profiles).
--    Bcrypt hash of "demo1234" generated with cost=10.
do $$
declare
  v_user1_id uuid := '99999999-9999-9999-9999-999999999901';
  v_user2_id uuid := '99999999-9999-9999-9999-999999999902';
  -- bcrypt cost 10 of 'demo1234'. Checked with bcryptjs: this hash accepts
  -- 'demo1234' and rejects 'password', 'demo123', 'demo12345'.
  -- (The previous constant was the widely-copied example hash and matched none
  -- of those, so the demo accounts could not be signed into.)
  v_bcrypt   text := '$2a$10$2f4vxsLXeQqoQ8AuQq91pO6ZHDflPlNddDnOLlYOmt6POkqSuzoZq';
begin
  -- Delete if previously seeded (so re-running is idempotent)
  delete from auth.users where id in (v_user1_id, v_user2_id);

  insert into auth.users (
    instance_id, id, aud, role, email,
    encrypted_password, email_confirmed_at,
    raw_app_meta_data, raw_user_meta_data,
    created_at, updated_at,
    confirmation_token, email_change, email_change_token_new, recovery_token
  ) values
    (
      '00000000-0000-0000-0000-000000000000',
      v_user1_id,
      'authenticated',
      'authenticated',
      'demo@uangku.app',
      v_bcrypt,
      now(),
      '{"provider":"email","providers":["email"]}'::jsonb,
      '{"full_name":"Ahmad Fauzan Ramadhani"}'::jsonb,
      now(), now(),
      '', '', '', ''
    ),
    (
      '00000000-0000-0000-0000-000000000000',
      v_user2_id,
      'authenticated',
      'authenticated',
      'demo2@uangku.app',
      v_bcrypt,
      now(),
      '{"provider":"email","providers":["email"]}'::jsonb,
      '{"full_name":"Putri Maharani"}'::jsonb,
      now(), now(),
      '', '', '', ''
    );

  raise notice 'Demo users created: demo@uangku.app / demo2@uangku.app (password: demo1234)';
end $$;

-- 3. Sample transactions so the home screen has data on first login.
--    Mix of income (allowance, freelance) and expense (food, transport, etc.)
do $$
declare
  v_user1_id uuid := '99999999-9999-9999-9999-999999999901';
  v_user2_id uuid := '99999999-9999-9999-9999-999999999902';
  v_today date := current_date;
  v_d date;
  v_items jsonb;
begin
  -- Wipe existing demo transactions (idempotent)
  delete from public.transactions where user_id in (v_user1_id, v_user2_id);

  -- User 1: Ahmad Fauzan - 30 days of realistic transactions
  for i in 0..29 loop
    v_d := v_today - i;

    -- expense: daily food (mostly)
    if i % 3 <> 0 then
      v_items := jsonb_build_array(
        jsonb_build_object('name','Nasi + Lauk','price', (15000 + (random()*5000)::int)::text),
        jsonb_build_object('name','Es Teh/Air Mineral','price', (3000 + (random()*2000)::int)::text)
      );
      insert into public.transactions (user_id, type, date, total, items, notes)
      values (
        v_user1_id, 'expense', v_d,
        (select sum((x->>'price')::numeric) from jsonb_array_elements(v_items) x),
        v_items, 'Makan siang/kampus'
      );
    end if;

    -- expense: transport every other day
    if i % 2 = 0 then
      v_items := jsonb_build_array(
        jsonb_build_object('name','Bensin/Transport','price', (10000 + (random()*10000)::int)::text)
      );
      insert into public.transactions (user_id, type, date, total, items, notes)
      values (
        v_user1_id, 'expense', v_d,
        (select sum((x->>'price')::numeric) from jsonb_array_elements(v_items) x),
        v_items, 'Transport kampus'
      );
    end if;

    -- income: monthly allowance (1st of month)
    if extract(day from v_d) = 1 then
      v_items := jsonb_build_array(
        jsonb_build_object('name','Uang Saku Bulanan','price', '1500000')
      );
      insert into public.transactions (user_id, type, date, total, items, notes)
      values (
        v_user1_id, 'income', v_d, 1500000, v_items, 'Uang saku dari orang tua'
      );
    end if;

    -- income: freelance project every 10 days
    if i % 10 = 5 then
      v_items := jsonb_build_array(
        jsonb_build_object('name','Freelance Web Project','price', (300000 + (random()*500000)::int)::text)
      );
      insert into public.transactions (user_id, type, date, total, items, notes)
      values (
        v_user1_id, 'income', v_d,
        (select sum((x->>'price')::numeric) from jsonb_array_elements(v_items) x),
        v_items, 'Project freelance'
      );
    end if;
  end loop;

  -- User 2: Putri Maharani - 30 days
  for i in 0..29 loop
    v_d := v_today - i;

    if i % 2 = 0 then
      v_items := jsonb_build_array(
        jsonb_build_object('name','Kopi & Snack','price', (12000 + (random()*8000)::int)::text),
        jsonb_build_object('name','Makan Siang','price', (18000 + (random()*7000)::int)::text)
      );
      insert into public.transactions (user_id, type, date, total, items, notes)
      values (
        v_user2_id, 'expense', v_d,
        (select sum((x->>'price')::numeric) from jsonb_array_elements(v_items) x),
        v_items, 'Jajan & makan'
      );
    end if;

    if extract(day from v_d) = 5 then
      v_items := jsonb_build_array(
        jsonb_build_object('name','Uang Saku','price', '2000000')
      );
      insert into public.transactions (user_id, type, date, total, items, notes)
      values (
        v_user2_id, 'income', v_d, 2000000, v_items, 'Transfer dari ortu'
      );
    end if;

    if i % 7 = 0 then
      v_items := jsonb_build_array(
        jsonb_build_object('name','Part-time Tutor','price', '150000')
      );
      insert into public.transactions (user_id, type, date, total, items, notes)
      values (
        v_user2_id, 'income', v_d, 150000, v_items, 'Les privat'
      );
    end if;
  end loop;
end $$;

-- 4. Summary
do $$
declare
  v_users int;
  v_profiles int;
  v_tx int;
begin
  select count(*) into v_users from auth.users where email like 'demo%@uangku.app';
  select count(*) into v_profiles from public.profiles where email like 'demo%@uangku.app';
  select count(*) into v_tx from public.transactions;

  raise notice 'Demo seed summary:';
  raise notice '  demo auth users     = %', v_users;
  raise notice '  demo profiles       = %', v_profiles;
  raise notice '  total transactions  = %', v_tx;
end $$;

-- =====================================================================
-- Done.
