import 'dart:io';

/// Regenerates supabase/apply_all.sql by concatenating migrations/* then
/// seed/* in lexicographic order. Run from the repo root:
///   dart tool/gen_apply_all.dart
Future<void> main() async {
  final root = Directory.current.path;
  String p(String rel) => '$root${Platform.pathSeparator}$rel';
  final migrationsDir = Directory(p('supabase${Platform.pathSeparator}migrations'));
  final seedDir = Directory(p('supabase${Platform.pathSeparator}seed'));

  List<File> sqlFiles(Directory d) {
    if (!d.existsSync()) return [];
    final files = d
        .listSync()
        .whereType<File>()
        .where((f) => f.path.endsWith('.sql'))
        .toList()
      ..sort((a, b) => a.path.compareTo(b.path));
    return files;
  }

  final migrations = sqlFiles(migrationsDir);
  final seeds = sqlFiles(seedDir);
  if (migrations.isEmpty) {
    stderr.writeln('No migrations found in ${migrationsDir.path}');
    exit(1);
  }

  final out = StringBuffer()
    ..writeln('-- =====================================================================')
    ..writeln('-- svings — complete schema + demo data, in one script.')
    ..writeln('--')
    ..writeln('-- Generated by `dart tool/gen_apply_all.dart` from supabase/migrations/*')
    ..writeln('-- then supabase/seed/* in lexicographic order. Do not edit here; edit the')
    ..writeln('-- source files and re-run the generator, otherwise this copy drifts.')
    ..writeln('--')
    ..writeln('-- HOW TO APPLY (no CLI, no password):')
    ..writeln('--   Supabase Dashboard -> SQL Editor -> New query -> paste this whole file -> Run')
    ..writeln('--')
    ..writeln('-- Safe to re-run? The migrations are idempotent (create table if not exists,')
    ..writeln('-- create or replace, type creation guarded by exception handlers). The SEED is')
    ..writeln('-- not: it deletes and recreates the demo users\' rows. Only re-run the whole')
    ..writeln('-- thing against a database whose data you are happy to reset.')
    ..writeln('-- =====================================================================')
    ..writeln();

  for (final f in [...migrations, ...seeds]) {
    final name = f.uri.pathSegments.skipWhile((s) => s != 'supabase').skip(1).join('/');
    out
      ..writeln()
      ..writeln('-- #####################################################################')
      ..writeln('-- ## $name')
      ..writeln('-- #####################################################################')
      ..writeln()
      ..writeln(f.readAsStringSync().trimRight())
      ..writeln();
  }

  File(p('supabase${Platform.pathSeparator}apply_all.sql'))
      .writeAsStringSync(out.toString());
  stdout.writeln(
      'Wrote supabase/apply_all.sql from ${migrations.length} migration(s) + ${seeds.length} seed(s).');
}
